name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install bison cmake catch2 flex
    - name: Build
      run: mkdir build && cd build && cmake .. && make splc -j2
    # - name: Unit Tests
    #   run: make unit-test
    # - name: Diff Tests
    #   run: make diff-test
